---
- hosts: masters
  vars_files:
  - ../env_variables 
  tasks:
  - name: Resetting Kubernetes cluster
    shell: kubeadm reset -f
  
  - name: Check if port 6443 is in use
    shell: "netstat -tuln | grep 6443"
    register: port_check
    ignore_errors: true

  - name: Kill the process using port 6443
    shell: "fuser -k 6443/tcp"
    when: port_check.rc == 0
    become: yes
  
  - name: Check if port 10250 is in use
    shell: "netstat -tuln | grep 10250"
    register: port_check
    ignore_errors: true

  - name: Kill the process using port 10250
    shell: "fuser -k 10250/tcp"
    when: port_check.rc == 0
    become: yes

  - name: Removing Kubernetes configuration directory
    shell: rm -rf $HOME/.kube

kubeadm init --pod-network-cidr=10.0.0.0/16 --kubernetes-version=v1.29 --ignore-preflight-errors=NumCPU --upload-certs --apiserver-cert-extra-sans 10.0.0.2

kubeadm join 188.245.41.48:6443 --token 7xcuoz.qf06qf3awdar5m3r --discovery-token-ca-cert-hash sha256:5d00b7519721d1ed70f4097706494db082fd6eca6a3e5a14abe38b2a59d43c19